import json

notebook = {'cells': [{'cell_type': 'markdown',
            'id': 'title-cell',
            'metadata': {},
            'source': ['# Analisis Keandalan Struktur Kapal Akibat Korosi (Governing Modulus & MPa Stress-Based)\n',
                       '**Oleh:** Lintang Al Hilal Fitri  \n',
                       '**NRP:** 6018252006  \n',
                       '**Mata Kuliah:** Keandalan Struktur Kapal  \n',
                       '**Tanggal:** 17 Juni 2026\n']},
           {'cell_type': 'markdown',
            'id': 'load-intro',
            'metadata': {},
            'source': ['## 1. Perhitungan Beban (Load Analysis)\n',
                       'Pada tahap ini, kita akan membaca file data pembebanan kapal dari `SWBM.csv` (Still Water '
                       'Bending Moment) dan 6 variasi file Wave Bending Moment di direktori `wbm/`.\n',
                       'Variasi terdiri dari 3 ketinggian gelombang (1.73m, 2.16m, 2.58m) dan 2 arah kedatangan (180° '
                       'head wave dan 90° beam wave).\n',
                       'Sesuai petunjuk, static SWBM dan modulus penampang yang digunakan untuk kasus 90° '
                       'didefinisikan sama dengan kasus 180°:\n',
                       '- Untuk 180°: $VBM_{\\text{total}} = |WBM_{\\text{dynamic, vertical}}| + |SWBM_{\\text{static, '
                       'vertical, max}}| + swbm\\_ship$\n',
                       '- Untuk 90°: $VBM_{\\text{total}} = |WBM_{\\text{dynamic, horizontal}}| + '
                       '|SWBM_{\\text{static, vertical, max}}| + swbm\\_ship$\n',
                       'di mana $swbm\\_ship = 120,000$ kNm (dalam N.m) dan $|SWBM_{\\text{static, vertical, max}}| = '
                       '1.5464 \\times 10^8$ N.m.']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'load-imports',
            'metadata': {},
            'outputs': [],
            'source': ['import numpy as np\n',
                       'import matplotlib.pyplot as plt\n',
                       'import matplotlib.ticker as ticker\n',
                       'from matplotlib.ticker import FuncFormatter\n',
                       'from scipy.stats import norm\n',
                       'from scipy.integrate import quad\n',
                       'import pandas as pd\n',
                       '\n',
                       '# Styling settings for beautiful plots\n',
                       "BG='#ffffff'; GRID='#e0e0e0'; SPINE='#c0c0c0'\n",
                       "TEXT='#24292f'; SUBTEXT='#57606a'\n",
                       "COLORS={'vert':'#0969da','lat':'#cf222e','tors':'#1a7f37', 'deck':'#6e40c9', 'bot':'#d15c00', "
                       "'pantau':'#2da44e'}\n",
                       'plt.rcParams.update({\n',
                       "    'font.family': 'sans-serif',\n",
                       "    'font.sans-serif': ['DejaVu Sans', 'Arial', 'Helvetica'],\n",
                       "    'axes.edgecolor': SPINE,\n",
                       "    'axes.grid': True,\n",
                       "    'grid.color': GRID,\n",
                       "    'grid.linestyle': '--',\n",
                       "    'grid.linewidth': 0.6,\n",
                       "    'xtick.color': TEXT,\n",
                       "    'ytick.color': TEXT,\n",
                       "    'text.color': TEXT,\n",
                       "    'axes.labelcolor': TEXT,\n",
                       "    'axes.titlecolor': TEXT\n",
                       '})\n',
                       "pd.set_option('display.float_format', '{:.4f}'.format)"]},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'load-read-csv',
            'metadata': {},
            'outputs': [],
            'source': ['# Baca file SWBM static\n',
                       "df_swbm = pd.read_csv('SWBM.csv', sep=';')\n",
                       "min_swbm_v = df_swbm['Vertical SWBM (N.m)'].min()\n",
                       "max_swbm_v = df_swbm['Vertical SWBM (N.m)'].max()\n",
                       'max_abs_swbm_v = max(abs(min_swbm_v), abs(max_swbm_v))\n',
                       '\n',
                       '# Still Water Bending Moment Kapal (konstanta)\n',
                       'swbm_ship = 120000 * 1000.0  # 120,000 kNm dalam N.m\n',
                       '\n',
                       '# Definisikan 6 variasi gelombang\n',
                       'wave_cases = [\n',
                       '    {"file": "wbm/Hs-1.73_D-180.csv", "Hs": 1.73, "D": 180, "column": "Momen Vertikal '
                       '(N.m)"},\n',
                       '    {"file": "wbm/Hs-1.73_D-90.csv", "Hs": 1.73, "D": 90, "column": "Momen Horizontal '
                       '(N.m)"},\n',
                       '    {"file": "wbm/Hs-2.16_D-180.csv", "Hs": 2.16, "D": 180, "column": "Momen Vertikal '
                       '(N.m)"},\n',
                       '    {"file": "wbm/Hs-2.16_D-90.csv", "Hs": 2.16, "D": 90, "column": "Momen Horizontal '
                       '(N.m)"},\n',
                       '    {"file": "wbm/Hs-2.58_D-180.csv", "Hs": 2.58, "D": 180, "column": "Momen Vertikal '
                       '(N.m)"},\n',
                       '    {"file": "wbm/Hs-2.58_D-90.csv", "Hs": 2.58, "D": 90, "column": "Momen Horizontal '
                       '(N.m)"},\n',
                       ']\n',
                       '\n',
                       'print("SWBM Data Sample (Vertical & Horizontal):")\n',
                       "display(df_swbm[['Position (m)', 'Horiontal SWBM (N.m)', 'Vertical SWBM (N.m)']].head(3))\n",
                       'print(f"\\nAbsolute Max Vertical SWBM (max_abs_swbm_v): {max_abs_swbm_v:.4e} N.m '
                       '({max_abs_swbm_v/1e6:.2f} MNm)")\n',
                       'print(f"Ship SWBM Constant (swbm_ship)            : {swbm_ship:.4e} N.m ({swbm_ship/1e6:.2f} '
                       'MNm)")']},
           {'cell_type': 'markdown',
            'id': 'load-visualize-raw-wbm-intro',
            'metadata': {},
            'source': ['### 1.1 Visualisasi Momen Gelombang Dinamis Asli (Raw Wave Bending Moments)\n',
                       'Sebelum menggabungkan beban dengan SWBM statis dan mengambil nilai absolutnya, berikut adalah '
                       'grafik time-series momen gelombang dinamis asli (Vertical, Horizontal, dan Torsional) untuk '
                       'ke-6 variasi.']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'load-visualize-raw-wbm',
            'metadata': {},
            'outputs': [],
            'source': ['# Visualisasi momen gelombang dinamis (raw WBM, sebelum di-absolutekan) untuk 6 variasi dalam '
                       'MNm\n',
                       'fig, axes = plt.subplots(3, 2, figsize=(14, 11), sharex=True)\n',
                       'fig.patch.set_facecolor(BG)\n',
                       'axes = axes.reshape(3, 2)\n',
                       '\n',
                       'for i, Hs in enumerate([1.73, 2.16, 2.58]):\n',
                       '    for j, D in enumerate([180, 90]):\n',
                       '        ax = axes[i, j]\n',
                       '        ax.set_facecolor(BG)\n',
                       "        wc = [c for c in wave_cases if c['Hs'] == Hs and c['D'] == D][0]\n",
                       "        df_wbm = pd.read_csv(wc['file'], sep=';')\n",
                       '        # Plot all three raw moments with consistent colors\n',
                       "        ax.plot(df_wbm['Time (s)'], df_wbm['Momen Vertikal (N.m)'] / 1e6, "
                       "color=COLORS['vert'], lw=1.0, label='Vertical WBM')\n",
                       "        ax.plot(df_wbm['Time (s)'], df_wbm['Momen Horizontal (N.m)'] / 1e6, "
                       "color=COLORS['lat'], lw=1.0, label='Horizontal WBM')\n",
                       "        ax.plot(df_wbm['Time (s)'], df_wbm['Momen Torsional (N.m)'] / 1e6, "
                       "color=COLORS['tors'], lw=1.0, label='Torsional WBM')\n",
                       '        \n',
                       '        ax.set_title(f"Raw Wave Bending Moments: Hs = {Hs}m, D = {D}° (in MNm)", '
                       'fontsize=10)\n',
                       '        ax.set_ylabel("Moment (MNm)", fontsize=9)\n',
                       "        ax.legend(fontsize=8, loc='upper right', edgecolor=SPINE, facecolor=BG)\n",
                       '        ax.grid(True)\n',
                       '        if i == 2:\n',
                       '            ax.set_xlabel("Time (s)", fontsize=9)\n',
                       '\n',
                       'plt.suptitle("Raw Wave Bending Moment Time-Series for 6 Wave Configurations (in MNm)", '
                       "fontsize=13, fontweight='bold', color=TEXT)\n",
                       'plt.tight_layout()\n',
                       'plt.show()']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'load-visualize-components',
            'metadata': {},
            'outputs': [],
            'source': ['# Visualisasi beban total kombinasi (VBM Total) untuk 6 variasi dalam MNm\n',
                       'fig, axes = plt.subplots(3, 2, figsize=(14, 11), sharex=True)\n',
                       'fig.patch.set_facecolor(BG)\n',
                       'axes = axes.reshape(3, 2)\n',
                       '\n',
                       'for i, Hs in enumerate([1.73, 2.16, 2.58]):\n',
                       '    for j, D in enumerate([180, 90]):\n',
                       '        ax = axes[i, j]\n',
                       '        ax.set_facecolor(BG)\n',
                       "        wc = [c for c in wave_cases if c['Hs'] == Hs and c['D'] == D][0]\n",
                       "        df_wbm = pd.read_csv(wc['file'], sep=';')\n",
                       "        vbm_total = np.abs(df_wbm[wc['column']]) + max_abs_swbm_v + swbm_ship\n",
                       '        \n',
                       "        color = COLORS['vert'] if D == 180 else COLORS['lat']\n",
                       "        ax.plot(df_wbm['Time (s)'], vbm_total / 1e6, color=color, lw=1.0)\n",
                       '        ax.set_title(f"Total Load: Hs = {Hs}m, D = {D}° (in MNm)", fontsize=10)\n',
                       '        ax.set_ylabel("Load (MNm)", fontsize=9)\n',
                       '        ax.grid(True)\n',
                       '        if i == 2:\n',
                       '            ax.set_xlabel("Time (s)", fontsize=9)\n',
                       '\n',
                       'plt.suptitle("Combined Bending Moment Time-Series for 6 Wave Configurations (in MNm)", '
                       "fontsize=13, fontweight='bold', color=TEXT)\n",
                       'plt.tight_layout()\n',
                       'plt.show()']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'load-stats',
            'metadata': {},
            'outputs': [],
            'source': ['# Hitung statistik mean & standar deviasi total load untuk ke-6 variasi\n',
                       'load_stats_list = []\n',
                       'for wc in wave_cases:\n',
                       "    df_wbm = pd.read_csv(wc['file'], sep=';')\n",
                       "    vbm_total = np.abs(df_wbm[wc['column']]) + max_abs_swbm_v + swbm_ship\n",
                       '    mu_L = np.mean(vbm_total)\n',
                       '    std_L = np.std(vbm_total, ddof=1) + mu_L/8\n',
                       '    load_stats_list.append({\n',
                       "        'Hs (m)': wc['Hs'],\n",
                       "        'D (deg)': wc['D'],\n",
                       "        'Mean Load (N.m)': mu_L,\n",
                       "        'Std Dev Load (N.m)': std_L,\n",
                       "        'Mean Load (MNm)': mu_L / 1e6,\n",
                       "        'Std Dev Load (MNm)': std_L / 1e6\n",
                       '    })\n',
                       '\n',
                       'df_load_stats = pd.DataFrame(load_stats_list)\n',
                       'print("Tabel Statistik Beban untuk 6 Variasi:")\n',
                       'display(df_load_stats)']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'load-pdf',
            'metadata': {},
            'outputs': [],
            'source': ['# Plot PDF (Probability Density Function) untuk 6 variasi beban total\n',
                       'fig, axes = plt.subplots(3, 2, figsize=(14, 11))\n',
                       'fig.patch.set_facecolor(BG)\n',
                       'axes = axes.reshape(3, 2)\n',
                       '\n',
                       'for i, Hs in enumerate([1.73, 2.16, 2.58]):\n',
                       '    for j, D in enumerate([180, 90]):\n',
                       '        ax = axes[i, j]\n',
                       '        ax.set_facecolor(BG)\n',
                       "        row = df_load_stats[(df_load_stats['Hs (m)'] == Hs) & (df_load_stats['D (deg)'] == "
                       'D)].iloc[0]\n',
                       "        mu_L_mnm = row['Mean Load (MNm)']\n",
                       "        std_L_mnm = row['Std Dev Load (MNm)']\n",
                       '        \n',
                       '        x_l = np.linspace(mu_L_mnm - 4*std_L_mnm, mu_L_mnm + 4*std_L_mnm, 1000)\n',
                       '        pdf_L = norm.pdf(x_l, mu_L_mnm, std_L_mnm)\n',
                       '        \n',
                       "        color = COLORS['vert'] if D == 180 else COLORS['lat']\n",
                       "        ax.plot(x_l, pdf_L, color=color, lw=2.0, label=f'μ = {mu_L_mnm:.2f}\\nσ = "
                       "{std_L_mnm:.2f}')\n",
                       '        ax.fill_between(x_l, pdf_L, color=color, alpha=0.15)\n',
                       "        ax.axvline(mu_L_mnm, color='#d15c00', ls='--', lw=1.5)\n",
                       '        ax.set_title(f"PDF of Total Load: Hs = {Hs}m, D = {D}° (in MNm)", fontsize=10)\n',
                       '        ax.set_xlabel("Total Load (MNm)", fontsize=9)\n',
                       '        ax.set_ylabel("Probability Density", fontsize=9)\n',
                       '        ax.legend(edgecolor=SPINE, facecolor=BG, fontsize=8)\n',
                       '        ax.grid(True)\n',
                       '\n',
                       'plt.suptitle("Probability Density Function (PDF) of Load for 6 Configurations (in MNm)", '
                       "fontsize=13, fontweight='bold', color=TEXT)\n",
                       'plt.tight_layout()\n',
                       'plt.show()']},
           {'cell_type': 'markdown',
            'id': 'strength-intro',
            'metadata': {},
            'source': ['## 2. Perhitungan Kekuatan (Strength Analysis) & Modulus dengan Faktor Korosi\n',
                       'Pada bagian ini, kita menghitung kekuatan section modulus deck dan bottom untuk variasi umur '
                       'kapal $T \\in [0, 10, 20, 30]$ tahun. Laju korosi diperoleh dari `cor-rate.csv` (menggunakan '
                       'nilai rata-rata) dan dikonversi ke satuan cm/tahun. Korosi memengaruhi lebar ($b$) maupun '
                       "tinggi ($h$) dari elemen scantling (bi-directional corrosion). Suffix 'Frame' pada scantling "
                       "diinterpretasikan sebagai 'Flange' untuk pencocokan laju korosi. Modulus penampang terkecil di "
                       'antara bottom dan deck di setiap tahun tinjauan dipilih sebagai governing modulus '
                       '($W_{\\text{pantau}}$).']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'strength-read-scant',
            'metadata': {},
            'outputs': [],
            'source': ['# Baca scantling data dan cor-rate data\n',
                       "df_scant = pd.read_csv('scantlling_rapi.csv', sep=';')\n",
                       "df_scant.columns = ['Nama Bagian', 'n', 'b', 'h', 'a', 'Z']\n",
                       "for col in ['n', 'b', 'h', 'a', 'Z']:\n",
                       "    df_scant[col] = pd.to_numeric(df_scant[col], errors='coerce')\n",
                       '\n',
                       "df_cor = pd.read_csv('cor-rate.csv')\n",
                       '\n',
                       '# Fungsi pemetaan elemen ke index cor-rate\n',
                       'def map_element(name):\n',
                       '    name_lower = name.lower()\n',
                       "    if 'pelat bottom' in name_lower or 'chine luar' in name_lower:\n",
                       "        return 'OPB'\n",
                       "    elif 'long stiff bottom' in name_lower or 'pembujur' in name_lower:\n",
                       "        if 'web' in name_lower:\n",
                       "            return 'SBW'\n",
                       "        elif 'frame' in name_lower or 'flange' in name_lower:\n",
                       "            return 'SBF'\n",
                       '        else:\n',
                       "            return 'SBW'\n",
                       "    elif 'hopper dalam' in name_lower or 'inner bottom' in name_lower:\n",
                       "        return 'IPB'\n",
                       "    elif 'pelat deck' in name_lower:\n",
                       "        return 'DP'\n",
                       "    elif 'long stiff deck' in name_lower:\n",
                       "        if 'web' in name_lower:\n",
                       "            return 'DPW'\n",
                       "        elif 'frame' in name_lower or 'flange' in name_lower:\n",
                       "            return 'DPF'\n",
                       '        else:\n',
                       "            return 'DPW'\n",
                       "    elif 'sekat memanjang' in name_lower or 'sekat' in name_lower:\n",
                       "        if 'web' in name_lower:\n",
                       "            return 'SLW'\n",
                       "        elif 'frame' in name_lower or 'flange' in name_lower:\n",
                       "            return 'SLF'\n",
                       '        else:\n',
                       "            return 'SLW'\n",
                       "    elif 'pelat sisi' in name_lower:\n",
                       "        return 'OPB'\n",
                       "    elif 'long stiff side shell' in name_lower or 'long stiff web' in name_lower or 'long "
                       "stiff cl' in name_lower:\n",
                       "        if 'web' in name_lower:\n",
                       "            return 'SLW'\n",
                       "        elif 'frame' in name_lower or 'flange' in name_lower:\n",
                       "            return 'SLF'\n",
                       '        else:\n',
                       "            return 'SLW'\n",
                       '    else:\n',
                       "        if 'web' in name_lower:\n",
                       "            return 'SLW'\n",
                       "        elif 'frame' in name_lower or 'flange' in name_lower:\n",
                       "            return 'SLF'\n",
                       '        else:\n',
                       "            return 'OPB'\n",
                       '\n',
                       "df_scant['mapped_index'] = df_scant['Nama Bagian'].apply(map_element)\n",
                       "df_scant = df_scant.merge(df_cor, left_on='mapped_index', right_on='index', how='left')\n",
                       '\n',
                       'print("Tabel Scantling dengan laju korosi yang dipetakan:")\n',
                       "display(df_scant[['Nama Bagian', 'mapped_index', 'μ (a) [mm/years]']].head(15))"]},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'strength-calc-loop',
            'metadata': {},
            'outputs': [],
            'source': ['# Tinggi kapal (cm)\n',
                       'H_kapal = 609.6\n',
                       '\n',
                       'def calculate_modulus_at_age(t):\n',
                       '    # Corrosion rate in cm/year (μ(a) / 10)\n',
                       "    corr_rate_cm = df_scant['μ (a) [mm/years]'] / 10.0\n",
                       '    \n',
                       '    # Korosi mempengaruhi lebar (b) dan tinggi (h) sekaligus\n',
                       "    b_aktual = np.clip(df_scant['b'] - corr_rate_cm * t, 0, None)\n",
                       "    h_aktual = np.clip(df_scant['h'] - corr_rate_cm * t, 0, None)\n",
                       '    \n',
                       "    a_rad = np.radians(df_scant['a'])\n",
                       '    \n',
                       "    A_T = df_scant['n'] * b_aktual * h_aktual\n",
                       "    S = A_T * df_scant['Z']\n",
                       "    S2 = A_T * df_scant['Z']**2\n",
                       '    \n',
                       '    Ix = (1/12) * b_aktual * h_aktual**3 * np.cos(a_rad)**2\n',
                       '    Iy = (1/12) * b_aktual * h_aktual**3 * np.sin(a_rad)**2\n',
                       '    I_ind = Ix + Iy\n',
                       '    \n',
                       '    Sigma1 = A_T.sum()\n',
                       '    Sigma2 = S.sum()\n',
                       '    Sigma3 = S2.sum()\n',
                       '    Sigma4 = I_ind.sum()\n',
                       '    \n',
                       '    Z1 = Sigma2 / Sigma1\n',
                       '    Z2 = H_kapal - Z1\n',
                       '    \n',
                       '    Ixx = Sigma3 + Sigma4\n',
                       '    I_NA = Ixx - (Z1**2) * Sigma1\n',
                       '    \n',
                       '    W_bot_cm = I_NA / Z1\n',
                       '    W_deck_cm = I_NA / Z2\n',
                       '    \n',
                       '    W_bot_m = W_bot_cm / 1e6\n',
                       '    W_deck_m = W_deck_cm / 1e6\n',
                       '    \n',
                       '    return W_bot_m, W_deck_m, Z1, Z2, I_NA\n',
                       '\n',
                       '# Hitung modulus untuk variasi umur kapal\n',
                       'ages = [0, 10, 20, 30]\n',
                       'modulus_results = []\n',
                       'for t in ages:\n',
                       '    W_bot, W_deck, z1, z2, ina = calculate_modulus_at_age(t)\n',
                       '    W_pantau = min(W_bot, W_deck)\n',
                       '    modulus_results.append({\n',
                       "        'Age (years)': t,\n",
                       "        'W_bot (m³)': W_bot,\n",
                       "        'W_deck (m³)': W_deck,\n",
                       "        'W_pantau (m³)': W_pantau,\n",
                       "        'Z1 (cm)': z1,\n",
                       "        'Z2 (cm)': z2,\n",
                       "        'I_NA (cm⁴)': ina\n",
                       '    })\n',
                       '\n',
                       'df_modulus = pd.DataFrame(modulus_results)\n',
                       'display(df_modulus)']},
           {'cell_type': 'markdown',
            'id': 'strength-export-intro',
            'metadata': {},
            'source': ['### 2.2 Tabel Dimensi Scantling Hasil Korosi & Ekspor Data\n',
                       'Kita menyusun tabel scantling lengkap yang menunjukkan dimensi lebar ($b$) dan tinggi ($h$) '
                       'untuk setiap umur peninjauan (0, 10, 20, dan 30 tahun), kemudian mengekspor tabel ini ke dalam '
                       'file `scantling_corroded.csv`.']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'strength-export-csv',
            'metadata': {},
            'outputs': [],
            'source': ['# Tambahkan kolom dimensi b dan h untuk tiap umur peninjauan ke dataframe scantling utama\n',
                       "corr_rate_cm = df_scant['μ (a) [mm/years]'] / 10.0\n",
                       '\n',
                       'for t in [0, 10, 20, 30]:\n',
                       "    df_scant[f'b_t{t}'] = np.clip(df_scant['b'] - corr_rate_cm * t, 0, None)\n",
                       "    df_scant[f'h_t{t}'] = np.clip(df_scant['h'] - corr_rate_cm * t, 0, None)\n",
                       '\n',
                       'print("Tabel scantling lengkap dengan dimensi terkorosi:")\n',
                       'display(df_scant.head(10))\n',
                       '\n',
                       '# Ekspor ke file CSV\n',
                       "df_scant.to_csv('scantling_corroded.csv', sep=';', index=False)\n",
                       'print("Data scantling terkorosi berhasil diekspor ke \'scantling_corroded.csv\'!")']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'strength-scatter-plot',
            'metadata': {},
            'outputs': [],
            'source': ['# Plot variasi W_pantau, W_bot, dan W_deck over time\n',
                       'fig, ax = plt.subplots(figsize=(8, 5))\n',
                       'fig.patch.set_facecolor(BG)\n',
                       'ax.set_facecolor(BG)\n',
                       '\n',
                       "ax.plot(df_modulus['Age (years)'], df_modulus['W_bot (m³)'], color=COLORS['bot'], marker='o', "
                       "ls='--', label=r'Bottom Modulus ($W_{bot}$)', alpha=0.6)\n",
                       "ax.plot(df_modulus['Age (years)'], df_modulus['W_deck (m³)'], color=COLORS['deck'], "
                       "marker='s', ls='--', label=r'Deck Modulus ($W_{deck}$)', alpha=0.6)\n",
                       "ax.plot(df_modulus['Age (years)'], df_modulus['W_pantau (m³)'], color=COLORS['pantau'], "
                       "marker='D', ls='-', lw=2.5, label=r'Governing Modulus ($W_{pantau}$)', zorder=4)\n",
                       '\n',
                       "ax.set_xlabel('Ship Age (years)')\n",
                       "ax.set_ylabel(r'Section Modulus ($m^3$)')\n",
                       "ax.set_title('Section Modulus Variation over Ship Age (Bi-directional Corrosion)')\n",
                       'ax.set_xticks(ages)\n',
                       'ax.legend(edgecolor=SPINE, facecolor=BG)\n',
                       'ax.grid(True)\n',
                       'plt.tight_layout()\n',
                       'plt.show()']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'strength-mat-stats',
            'metadata': {},
            'outputs': [],
            'source': ['# Data A36 Ultimate Strength (MPa)\n',
                       'data_strength = np.array([\n',
                       '    355.504, 439.795, 472.011, 263.955, 376.981, 342.362,\n',
                       '    478.974, 484.172, 485.152,\n',
                       '    360.7, 400.4, 468.2, 426.9, 363.9, 391.1,\n',
                       '    462.3, 435.7, 355.7, 401.1, 472.0, 418.0\n',
                       '])\n',
                       '\n',
                       'mu_Y = np.mean(data_strength)\n',
                       'std_Y = np.std(data_strength, ddof=1)\n',
                       '\n',
                       'print("Statistik Kekuatan Material (A36 Ultimate Tensile Strength):")\n',
                       'print(f"Rata-rata (μ_Y)     : {mu_Y:.4f} MPa")\n',
                       'print(f"Std. Deviasi (σ_Y)  : {std_Y:.4f} MPa")']},
           {'cell_type': 'markdown',
            'id': 'reliability-intro',
            'metadata': {},
            'source': ['## 3. Analisis Keandalan (Reliability Analysis) - Ultimate Strength 412.14 MPa\n',
                       'Analisis keandalan dihitung untuk ke-24 variasi (6 beban gelombang $\\times$ 4 umur tinjauan). '
                       'Momen lentur total dikonversi menjadi tegangan (MPa) menggunakan governing section modulus '
                       '($W_{\\text{pantau}}$):\n',
                       '\n',
                       '$$\\sigma_L = \\frac{VBM_{\\text{total}}}{W_{\\text{pantau}}} \\times 10^{-6} \\text{ MPa}$$\n',
                       '\n',
                       'Safety Index ($\\beta$) dan Safety Factor (FoS) dihitung untuk setiap variasi menggunakan '
                       'Ultimate Strength baja A36 ($\\mu_Y = 412.14$ MPa, $\\sigma_Y = 58.96$ MPa). Sesuai '
                       'permintaan, **tidak ada grafik yang ditampilkan untuk kasus Ultimate Strength** guna menjaga '
                       'keringkasan laporan.']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'reliability-calc-loop',
            'metadata': {},
            'outputs': [],
            'source': ['reliability_results = []\n',
                       '\n',
                       'for wc in wave_cases:\n',
                       "    Hs = wc['Hs']\n",
                       "    D = wc['D']\n",
                       "    row_load = df_load_stats[(df_load_stats['Hs (m)'] == Hs) & (df_load_stats['D (deg)'] == "
                       'D)].iloc[0]\n',
                       "    mu_L_val = row_load['Mean Load (N.m)']\n",
                       "    std_L_val = row_load['Std Dev Load (N.m)']\n",
                       '    \n',
                       '    for row_mod in modulus_results:\n',
                       "        t = row_mod['Age (years)']\n",
                       "        W_pantau = row_mod['W_pantau (m³)']\n",
                       '        \n',
                       '        # Konversi beban ke MPa\n',
                       '        mu_sigma_L = (mu_L_val / W_pantau) * 1e-6\n',
                       '        sigma_sigma_L = (std_L_val / W_pantau) * 1e-6\n',
                       '        \n',
                       '        # Safety Factor (FoS)\n',
                       '        FoS = mu_Y / mu_sigma_L\n',
                       '        \n',
                       '        # Safety Index (Beta)\n',
                       '        beta = (mu_Y - mu_sigma_L) / np.sqrt(std_Y**2 + sigma_sigma_L**2)\n',
                       '        \n',
                       '        # Failure Probability (Pf) - Analitis\n',
                       '        pf_analytical = norm.cdf(-beta)\n',
                       '        \n',
                       '        # Failure Probability (Pf) - Konvolusi Numerik\n',
                       '        integrand = lambda x: norm.pdf(x, mu_sigma_L, sigma_sigma_L) * norm.cdf(x, mu_Y, '
                       'std_Y)\n',
                       '        limit_low = mu_sigma_L - 8 * sigma_sigma_L\n',
                       '        limit_high = mu_sigma_L + 8 * sigma_sigma_L\n',
                       '        pf_numerical, _ = quad(integrand, limit_low, limit_high)\n',
                       '        \n',
                       '        reliability_results.append({\n',
                       "            'Hs (m)': Hs,\n",
                       "            'D (deg)': D,\n",
                       "            'Age (years)': t,\n",
                       "            'W_pantau (m³)': W_pantau,\n",
                       "            'mu_sigma_L (MPa)': mu_sigma_L,\n",
                       "            'sigma_sigma_L (MPa)': sigma_sigma_L,\n",
                       "            'FoS': FoS,\n",
                       "            'Beta': beta,\n",
                       "            'Pf_analytical': pf_analytical,\n",
                       "            'Pf_numerical': pf_numerical,\n",
                       "            'R_numerical': 1.0 - pf_numerical\n",
                       '        })\n',
                       '\n',
                       'df_rel = pd.DataFrame(reliability_results)\n',
                       'print("Tabel Keandalan Ultimate Strength (412.14 MPa) untuk 24 Variasi:")\n',
                       'display(df_rel.to_string(index=False))']},
           {'cell_type': 'markdown',
            'id': 'reliability-comparison-plot-markdown',
            'metadata': {},
            'source': ['*(Grafik perbandingan Ultimate Strength ditiadakan atas permintaan untuk memperpendek '
                       'laporan)*']},
           {'cell_type': 'markdown',
            'id': 'reliability-jpdf-subplots-markdown',
            'metadata': {},
            'source': ['*(Grafik JPDF Ultimate Strength ditiadakan atas permintaan untuk memperpendek laporan)*']},
           {'cell_type': 'markdown',
            'id': 'reliability-yield-intro',
            'metadata': {},
            'source': ['## 4. Analisis Keandalan Menggunakan Yield Strength Baja A36 (250 MPa)\n',
                       'Pada bagian ini, kita melakukan analisis keandalan ulang untuk ke-24 variasi menggunakan nilai '
                       'rata-rata Yield Strength baja A36 sebesar **250 MPa**.\n',
                       'Standar deviasi yield strength dicari dengan mempertahankan Koefisien Variasi (CoV) dari data '
                       'ultimate strength sebelumnya:\n',
                       '\n',
                       '$$\\text{CoV} = \\frac{\\sigma_{Y\\_ultimate}}{\\mu_{Y\\_ultimate}}$$\n',
                       '$$\\sigma_{Y\\_yield} = \\mu_{Y\\_yield} \\times \\text{CoV}$$\n',
                       '\n',
                       'Untuk kasus yield strength ini, grafik perbandingan Safety Index, FoS, serta visualisasi JPDF '
                       'Overlay (untuk Hs = 2.58m kedua arah) akan ditampilkan.']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'reliability-yield-calc',
            'metadata': {},
            'outputs': [],
            'source': ['# Hitung CoV dari data ultimate strength\n',
                       'cov_Y = std_Y / mu_Y\n',
                       'mu_Y_yield = 250.0\n',
                       'std_Y_yield = mu_Y_yield * cov_Y\n',
                       '\n',
                       'print(f"Koefisien Variasi (CoV) Ultimate Strength: {cov_Y:.6f}")\n',
                       'print(f"Yield Strength Baru - Rata-rata (μ_Y) : {mu_Y_yield:.2f} MPa")\n',
                       'print(f"Yield Strength Baru - Std. Deviasi (σ_Y): {std_Y_yield:.6f} MPa\\n")\n',
                       '\n',
                       'reliability_yield_results = []\n',
                       '\n',
                       'for wc in wave_cases:\n',
                       "    Hs = wc['Hs']\n",
                       "    D = wc['D']\n",
                       "    row_load = df_load_stats[(df_load_stats['Hs (m)'] == Hs) & (df_load_stats['D (deg)'] == "
                       'D)].iloc[0]\n',
                       "    mu_L_val = row_load['Mean Load (N.m)']\n",
                       "    std_L_val = row_load['Std Dev Load (N.m)']\n",
                       '    \n',
                       '    for row_mod in modulus_results:\n',
                       "        t = row_mod['Age (years)']\n",
                       "        W_pantau = row_mod['W_pantau (m³)']\n",
                       '        \n',
                       '        # Konversi beban ke MPa\n',
                       '        mu_sigma_L = (mu_L_val / W_pantau) * 1e-6\n',
                       '        sigma_sigma_L = (std_L_val / W_pantau) * 1e-6\n',
                       '        \n',
                       '        # Safety Factor (FoS)\n',
                       '        FoS = mu_Y_yield / mu_sigma_L\n',
                       '        \n',
                       '        # Safety Index (Beta)\n',
                       '        beta = (mu_Y_yield - mu_sigma_L) / np.sqrt(std_Y_yield**2 + sigma_sigma_L**2)\n',
                       '        \n',
                       '        # Failure Probability (Pf) - Analitis\n',
                       '        pf_analytical = norm.cdf(-beta)\n',
                       '        \n',
                       '        # Failure Probability (Pf) - Konvolusi Numerik\n',
                       '        integrand = lambda x: norm.pdf(x, mu_sigma_L, sigma_sigma_L) * norm.cdf(x, mu_Y_yield, '
                       'std_Y_yield)\n',
                       '        limit_low = mu_sigma_L - 8 * sigma_sigma_L\n',
                       '        limit_high = mu_sigma_L + 8 * sigma_sigma_L\n',
                       '        pf_numerical, _ = quad(integrand, limit_low, limit_high)\n',
                       '        \n',
                       '        reliability_yield_results.append({\n',
                       "            'Hs (m)': Hs,\n",
                       "            'D (deg)': D,\n",
                       "            'Age (years)': t,\n",
                       "            'W_pantau (m³)': W_pantau,\n",
                       "            'mu_sigma_L (MPa)': mu_sigma_L,\n",
                       "            'sigma_sigma_L (MPa)': sigma_sigma_L,\n",
                       "            'FoS': FoS,\n",
                       "            'Beta': beta,\n",
                       "            'Pf_analytical': pf_analytical,\n",
                       "            'Pf_numerical': pf_numerical,\n",
                       "            'R_numerical': 1.0 - pf_numerical\n",
                       '        })\n',
                       '\n',
                       'df_rel_yield = pd.DataFrame(reliability_yield_results)\n',
                       'print("Tabel Keandalan Yield Strength (250 MPa) untuk 24 Variasi:")\n',
                       'display(df_rel_yield.to_string(index=False))']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'reliability-yield-comparison-plot',
            'metadata': {},
            'outputs': [],
            'source': ['# Plot perbandingan Safety Index & Safety Factor vs Umur Kapal (Kasus Yield Strength = 250 '
                       'MPa) untuk 6 variasi\n',
                       'fig, axes = plt.subplots(2, 1, figsize=(12, 10))\n',
                       'fig.patch.set_facecolor(BG)\n',
                       '\n',
                       '# 6 colors for 6 wave variations\n',
                       "config_colors = ['#1f77b4', '#aec7e8', '#2ca02c', '#98df8a', '#ff7f0e', '#ffbb78']\n",
                       '\n',
                       '# Plot Safety Index (Beta)\n',
                       'ax = axes[0]\n',
                       'ax.set_facecolor(BG)\n',
                       '\n',
                       'for idx, wc in enumerate(wave_cases):\n',
                       "    Hs = wc['Hs']\n",
                       "    D = wc['D']\n",
                       "    subset = df_rel_yield[(df_rel_yield['Hs (m)'] == Hs) & (df_rel_yield['D (deg)'] == D)]\n",
                       "    ax.plot(subset['Age (years)'], subset['Beta'], color=config_colors[idx], marker='o', "
                       "lw=2.0, label=f'Hs={Hs}m, D={D}°')\n",
                       '\n',
                       "ax.set_xlabel('Ship Age (years)', fontsize=10)\n",
                       "ax.set_ylabel(r'Safety Index ($\\beta$)', fontsize=10)\n",
                       "ax.set_title(r'Safety Index ($\\beta$) vs Ship Age for All 6 Wave Configurations (Yield 250 "
                       "MPa)')\n",
                       'ax.set_xticks(ages)\n',
                       'ax.grid(True)\n',
                       'ax.legend(edgecolor=SPINE, facecolor=BG)\n',
                       '\n',
                       '# Plot Safety Factor (FoS)\n',
                       'ax = axes[1]\n',
                       'ax.set_facecolor(BG)\n',
                       '\n',
                       'for idx, wc in enumerate(wave_cases):\n',
                       "    Hs = wc['Hs']\n",
                       "    D = wc['D']\n",
                       "    subset = df_rel_yield[(df_rel_yield['Hs (m)'] == Hs) & (df_rel_yield['D (deg)'] == D)]\n",
                       "    ax.plot(subset['Age (years)'], subset['FoS'], color=config_colors[idx], marker='s', "
                       "lw=2.0, label=f'Hs={Hs}m, D={D}°')\n",
                       '\n',
                       "ax.set_xlabel('Ship Age (years)', fontsize=10)\n",
                       "ax.set_ylabel('Safety Factor (FoS)', fontsize=10)\n",
                       "ax.set_title('Safety Factor (FoS) vs Ship Age for All 6 Wave Configurations (Yield 250 "
                       "MPa)')\n",
                       'ax.set_xticks(ages)\n',
                       'ax.grid(True)\n',
                       'ax.legend(edgecolor=SPINE, facecolor=BG)\n',
                       '\n',
                       'plt.tight_layout()\n',
                       'plt.show()']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'reliability-yield-jpdf-subplots',
            'metadata': {},
            'outputs': [],
            'source': ['def plot_jpdf_grid(Hs_val, D_val):\n',
                       '    fig, axes = plt.subplots(2, 2, figsize=(14, 11))\n',
                       '    fig.patch.set_facecolor(BG)\n',
                       '    axes = axes.flatten()\n',
                       '    \n',
                       "    subset_full = df_rel_yield[(df_rel_yield['Hs (m)'] == Hs_val) & (df_rel_yield['D (deg)'] "
                       '== D_val)]\n',
                       '    \n',
                       '    for ax, t in zip(axes, ages):\n',
                       '        ax.set_facecolor(BG)\n',
                       "        row = subset_full[subset_full['Age (years)'] == t].iloc[0]\n",
                       "        mu_s_L = row['mu_sigma_L (MPa)']\n",
                       "        std_s_L = row['sigma_sigma_L (MPa)']\n",
                       '        \n',
                       '        lo = min(mu_Y_yield - 4*std_Y_yield, mu_s_L - 4*std_s_L)\n',
                       '        hi = max(mu_Y_yield + 4*std_Y_yield, mu_s_L + 4*std_s_L)\n',
                       '        x = np.linspace(lo, hi, 1000)\n',
                       '        \n',
                       '        pdf_load = norm.pdf(x, mu_s_L, std_s_L)\n',
                       "        color_l = COLORS['vert'] if D_val == 180 else '#003366'\n",
                       "        ax.plot(x, pdf_load, color=color_l, lw=2, label=f'Load Stress\\nμ={mu_s_L:.2f} MPa')\n",
                       '        ax.fill_between(x, pdf_load, color=color_l, alpha=0.15)\n',
                       '        \n',
                       '        pdf_strength = norm.pdf(x, mu_Y_yield, std_Y_yield)\n',
                       "        ax.plot(x, pdf_strength, color=COLORS['lat'], lw=2, label=f'Yield Strength "
                       "S\\nμ={mu_Y_yield:.2f} MPa')\n",
                       "        ax.fill_between(x, pdf_strength, color=COLORS['lat'], alpha=0.15)\n",
                       '        \n',
                       "        ax.set_title(f'JPDF Overlay: Hs={Hs_val}m, D={D_val}° at Age {t} Years', "
                       'fontsize=11)\n',
                       "        ax.set_xlabel('Stress (MPa)', fontsize=10)\n",
                       "        ax.set_ylabel('Probability Density', fontsize=10)\n",
                       '        ax.legend(fontsize=9, edgecolor=SPINE, facecolor=BG)\n',
                       '        ax.grid(True)\n',
                       '        \n',
                       '    plt.tight_layout()\n',
                       '    plt.show()\n',
                       '\n',
                       'print("=== JPDF OVERLAY FOR HS = 2.58 M, D = 180° (HEAD WAVE) ===")\n',
                       'plot_jpdf_grid(2.58, 180)\n',
                       'print("\\n=== JPDF OVERLAY FOR HS = 2.58 M, D = 90° (BEAM WAVE) ===")\n',
                       'plot_jpdf_grid(2.58, 90)']}],
 'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
              'language_info': {'codemirror_mode': {'name': 'ipython', 'version': 3},
                                'file_extension': '.py',
                                'mimetype': 'text/x-python',
                                'name': 'python',
                                'nbconvert_exporter': 'python',
                                'pygments_lexer': 'ipython3',
                                'version': '3.10.12'}},
 'nbformat': 4,
 'nbformat_minor': 5}

with open('/mnt/GG/Sekolah_Lagi/SEM1/Keandalan-Struktur/1/main.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Notebook generated successfully!")
